# conda env create -f environment.yaml

name: opioid_env

channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia

dependencies:

# Standard packages for running in VS Code
  - python
  - pip
  - jupyter

# Data manipulation
  - numpy
  - pandas
# Faster excel readers
  - openpyxl
  - python-calamine
  - pyarrow

# Data Plotting
  - matplotlib
  - seaborn
  - plotly

# Data Analysis and Model Buliding
  - scikit-learn
  - boruta_py # feature importance
  - scipy
  - statsmodels # May not work with due to OpenSSL error; Use pip

  # Deep Neural Networks
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  # - tensorflow

  # HuggingFace for NLP
  - transformers

# Documentation
  - sphinx


  - pip:
    # Pip items here
    - statsmodels